name: Update Visitor Counter

on:
  schedule:
    - cron: '0 0 * * *' # запускать каждый день в полночь UTC
  workflow_dispatch: # ручной запуск из интерфейса GitHub

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate SVG counter
        run: node generate_counter.js

      - name: Commit and push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add count.svg
          git commit -m "Update visitor counter"
          git push
        continue-on-error: true
